# Generated by Django 4.2.16 on 2024-11-23 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_movielike'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
